/**
 * Pluxee Icon Names — GERÇEK LİSTE
 *
 * Source: Pluxee CDN sprite.svg
 * https://visualassets.designsystem.pluxee.app/desy-assets/cdn-assets-prd/icons/sprite.svg
 *
 * Toplam: ~240 icon × 2 boyut (16, 24) = ~480 SVG dosyası
 *
 * CDN format: /icons/figma/{name}{size}.svg
 *   örn: house + 24 → /icons/figma/house24.svg
 *
 * Bu liste autocomplete + tip güvenliği sağlar.
 */

export const iconNames = [
  // ===== ACCESSIBILITY & USER =====
  'accessibility',
  'addUser',
  'avatar',
  'employee',
  'employeeGroup',
  'person',
  'removeUser',
  'userGroup',
  'elderyFemale',
  'elderyMale',

  // ===== NAVIGATION & ARROWS =====
  'arrowCurved',
  'arrowDown',
  'arrowDownLeft',
  'arrowDownRight',
  'arrowLeft',
  'arrowRight',
  'arrowUp',
  'arrowUpLeft',
  'arrowUpRight',
  'arrowsHorizontal',
  'arrowsHorizontalFilled',
  'arrowsHorizontalOutline',
  'arrowsVertical',
  'arrowsVerticalFilled',
  'arrowsVerticalOutline',
  'chevronDown',
  'chevronDownCircle',
  'chevronDownFilled',
  'chevronLeft',
  'chevronLeftCircle',
  'chevronLeftFilled',
  'chevronRight',
  'chevronRightCircle',
  'chevronRightFilled',
  'chevronUp',
  'chevronUpCircle',
  'chevronUpFilled',
  'chevronDoubleDownCircleOutline',
  'chevronDoubleLeftCircleOutline',
  'chevronDoubleRightCircleOutline',
  'chevronDoubleUpCircleOutline',
  'menu',
  'closeMenu',
  'xmark',
  'direction',
  'position',
  'externalLink',
  'return',

  // ===== ACTIONS =====
  'activate',
  'deactivate',
  'addComment',
  'backspace',
  'comment',
  'copy',
  'delete',
  'deleteCircleFilled',
  'deleteCircleOutline',
  'editOff',
  'erase',
  'fileDelete',
  'fileEdit',
  'paste',
  'pen',
  'print',
  'reorder',
  'refresh',
  'monetRefresh',
  'resizing',
  'share',
  'topUp',
  'translate',
  'trash',
  'upload',
  'download',
  'lineBreak',
  'draggable',

  // ===== CHECK / STATUS =====
  'check',
  'checkCircle',
  'checkOutline',
  'checklist',
  'checkmark',
  'cancelFilled',
  'blockCircleOutline',
  'connect',

  // ===== ALERTS / INFO =====
  'alert',
  'alertOutline',
  'info',
  'infoOutline',
  'warning',
  'warningOutline',
  'help',
  'question',
  'questionFilled',
  'qA',

  // ===== EYES / VISIBILITY =====
  'eyeCloseFilled',
  'eyeCloseOutline',
  'eyeOpenFilled',
  'eyeOpenOutline',

  // ===== SECURITY =====
  'lock',
  'lockFilled',
  'unlock',
  'key',
  'password',
  'fingerprint',
  'faceId',
  'privacy',
  'security',

  // ===== AUTH =====
  'login',
  'logout',
  'identification',

  // ===== FINANCIAL / CARDS =====
  'wallet',
  'walletLoading',
  'walletPlus',
  'walletRefresh',
  'walletSync',
  'cardCreditActivated',
  'cardPin',
  'cash',
  'cashback',
  'cashbackBis',
  'coinsUp',
  'dollar',
  'euro',
  'money',
  'moneyBagDollar',
  'moneyBagEuro',
  'eCheck',
  'echeque',
  'billing',
  'reimbursement',
  'expensesManagement',
  'voucher',
  'ticket',
  'ticketVariant',
  'sdxCard',
  'sdxCardPlus',
  'sdxCardSlashed',
  'qrCard',
  'qrCode',
  'qrPhone',

  // ===== PAYMENT METHODS =====
  'applePay',
  'mastercard',
  'visa',
  'paypal',
  'onlinePayment',
  'payment',
  'splitPayment',
  'splitPaymentActive',
  'splitPaymentDelete',
  'splitPaymentEnroll',
  'poS',
  'ccScan',
  'barCode',

  // ===== COMMUNICATION =====
  'mail',
  'phone',
  'chat',
  'talk',
  'notifications',
  'paperclip',

  // ===== FILES & DOCUMENTS =====
  'file',
  'folder',
  'pdf',
  'csv',
  'excel',
  'word',
  'unknownDoc',
  'notes',
  'book',
  'certificate',

  // ===== SOCIAL =====
  'facebook',
  'instagram',
  'linkedin',
  'twitter',
  'whatsapp',
  'youtube',
  'google',
  'microsoft',
  'apple',
  'android',
  'ssofacebook',

  // ===== MEAL / FOOD =====
  'meal',
  'mealFood',
  'food',
  'chef',
  'cutlery',
  'cookie',
  'chicken',
  'fish',
  'egg',
  'maize',
  'mustard',
  'celery',
  'sesame',
  'soybean',
  'peanut',
  'nut',
  'lupines',
  'mollusc',
  'schrimp',
  'spicy',
  'sulfites',
  'tetrapack',

  // ===== SHOPPING / STORE =====
  'shoppingBag',
  'shoppingCart',
  'shoppingCartAdd',
  'shopId',
  'store',
  'merchant',
  'priceTag',
  'gift',
  'promotions',
  'incentive',
  'loyaltyProgram',

  // ===== DELIVERY =====
  'delivery',
  'parcelDelivery',
  'parcelDeliveryBis',
  'clickCollect',
  'clickDelivery',

  // ===== TRANSPORTATION =====
  'airplane',
  'bike',
  'bus',
  'car',
  'scooter',
  'tramway',
  'walk',
  'wheel',
  'wheelFilled',
  'travel',
  'mobility',
  'fuel',
  'fleet',

  // ===== HOME & LOCATION =====
  'house',
  'homeLocation',
  'homeOffice',
  'homeWifi',
  'office',
  'workBriefcase',
  'pin',
  'pinFilled',
  'pinOutline',
  'globe',
  'city',
  'path',

  // ===== TIME / CALENDAR =====
  'calendar',
  'calendarMonth',
  'calendarToday',
  'calendarWarning',
  'calendarYear',
  'clock',
  'clockAlternative',
  'clockAlternativeFilled',
  'history',
  'hourglass',

  // ===== HEALTH / WELLNESS =====
  'health',
  'wellness',
  'wellbeing',
  'medicalKit',
  'careSolidarity',
  'childCare',
  'yoga',
  'football',
  'sportCulture',

  // ===== DEVICES =====
  'mobile',
  'tablet',
  'laptop',
  'screen',
  'display',
  'wifi',
  'wifiOff',
  'cloud',
  'rss',
  'sound',
  'telecommunication',

  // ===== EMOJIS & FEEDBACK =====
  'emojiNeutral',
  'emojiSad',
  'emojiSmile',
  'thumbDown',
  'thumbUp',
  'heartFilled',
  'heartOutline',
  'starFilled',
  'starFilledCircle',
  'starOutline',
  'starOutlineCircle',
  'medal',
  'crown',
  'diamond',
  'rocket',
  'confetti',
  'applause',
  'claps',

  // ===== UI / FORMATTING =====
  'bold',
  'bulletlist',
  'listview',
  'dashboard',
  'filter',
  'filterApplied',
  'serachFilter',
  'search',
  'sortingDown',
  'sortingNeutral',
  'sortingUp',
  'clickableSortingDown',
  'clickableSortingNeutral',
  'clickableSortingUp',
  'threeDotsHorizontal',
  'threeDotsVertical',
  'openParenthesis',
  'closeParenthesis',
  'plus',
  'plusCircleFilled',
  'plusCircleOutline',
  'minus',
  'minusCircleFilled',
  'minusCircleOutline',
  'equals',
  'equalsCircleFilled',
  'multiply',
  'divide',
  'exchange',
  'onOff',
  'switchOn',
  'switchOff',

  // ===== CHARTS / DATA =====
  'curveChart',
  'pieChart',
  'stats',
  'activity',
  'consumption',
  'engagement',
  'optimize',
  'target',

  // ===== ENERGY / NATURE =====
  'bolt',
  'boltOff',
  'eco',
  'electricity',
  'flame',
  'flake',
  'carbonfootprint',

  // ===== MISC =====
  'settings',
  'settingsBis',
  'receipt',
  'play',
  'camera',
  'picture',
  'mixed',
  'flexibleBenefit',
  'multiBenefits',
  'culture',
  'leisure',
  'training',
  'meeting',
  'associate',
  'bulk',
  'clothing',
  'conciergerie',
  'grosseryShopping',
  'petPaw',
  'uniform',
  'waiter',
] as const;

export type IconName = (typeof iconNames)[number];
